spring:
  application:
    name: experiments
    admin:
      enabled: true
  data:
    mongodb:
      username: test
      password: test
      uri: mongodb://localhost:27017/test

management:
  health:
    defaults:
      enabled: true
    mongo:
      enabled: true
  server:
    port: 8090
  endpoint:
    health:
      probes:
        enabled: true
        add-additional-paths: true
  otlp:
    tracing:
      export:
        enabled: false
    logging:
      export:
        enabled: false
    metrics:
      export:
        enabled: false